CREATE TABLE merchant_category_cache (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         merchant_key VARCHAR(255) NOT NULL UNIQUE,
                                         category VARCHAR(30) NOT NULL,
                                         source VARCHAR(10) NOT NULL,
                                         confidence DOUBLE PRECISION NOT NULL,
                                         last_seen TIMESTAMP NOT NULL,
                                         created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_merchant_cache_name ON merchant_category_cache (merchant_key);